config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "home#index"

  get "/buy/:id", to: "home#checkout", as: "checkout"
  post "/buy/:id", to: "home#buy", as: "buy"

  delete "/cancel_ticket/:id", to: "home#cancel_user_ticket", as: "cancel_ticket"

  get "/user_tickets", to: "home#user_tickets"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :transports
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :transport
end

app/models/transport.rb
class Transport < ApplicationRecord
  belongs_to :company

  has_many :tickets, dependent: :destroy
  has_many :users, through: :tickets
end

app/models/user.rb
class User < ApplicationRecord

  has_many :tickets, dependent: :destroy
  has_many :transports, through: :tickets

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!, except: [:index]

    # Shows all available transports - doesn't show past transports
    def index
      @transports = []
      tmp_transport = Transport.order("departure ASC")
      current_time = Time.new()
      tmp_transport.each do |tmp_transport|
        if tmp_transport.departure > current_time
          @transports.append(tmp_transport)
        end
      end
    end

    # Shows all tickets purchased by a user - only future ones
    def user_tickets
      @tickets = []
      tmp_tickets = current_user.tickets
      current_time = Time.new()
      tmp_tickets.each do |tmp_ticket|
        if tmp_ticket.transport.departure > current_time
          @tickets.append(tmp_ticket)
        end
      end
    end

    # Cancels a ticket if there is more than an hour until departure
    # Deletes ticket from database
    def cancel_user_ticket
        @ticket = Ticket.find(params[:id])
        if (@ticket.transport.departure - Time.new()) > 3600
          @ticket.destroy
          redirect_to user_tickets_path, notice: "Otkazana karta!"
        else
          redirect_to user_tickets_path, notice: "Nije moguce otkazati kartu sat vremena prije poslaska!"
        end
        
    end

    # Buy menu
    def checkout
        @transport = Transport.find(params[:id])
    end

    # Checks all conditions and inserts ticket into database
    def buy
        @transport = Transport.find(params[:id])
        @ticket = Ticket.new(user: current_user, transport: @transport, name: params[:input_name] , email: params[:input_email])

        # Check transport is in the future
        if @transport.departure > Time.new()
          # Check available tickets
          if @transport.nTickets - @transport.tickets.length > 0
            # Check card number
            if params[:input_card_num].length > 10
              # Check name
              if params[:input_name].length > 2
                # Check email
                if params[:input_email].length > 5

                  if @ticket.save # Save ticket to database
                    redirect_to user_tickets_path, notice: "Uspjesno kupljena karta."
                  else
                      redirect_to root_path, notice: "Transakcija neuspjela! Karta nije kupljena."
                  end

                else
                  redirect_to root_path, notice: "Morate unijeti email!"
                end
              else
                redirect_to root_path, notice: "Morate unijeti ime!"
              end
            else
              redirect_to root_path, notice: "Morate unijeti broj kartice!"
            end
          else
            redirect_to root_path, notice: "Sve karte su rasprodane! Karta nije kupljena."
          end
        else
          redirect_to root_path, notice: "Nije moguce kupiti karte u proslosti!"
        end
      end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/checkout.html.erb
<div class="container">
  <div class="row gy-5">
    <div class="col p-3 border bg-light">
      <h1>Podatci</h1>
      <%= form_with url: @transport.id.to_s do |form| %>
        <div class="mb-3">
          <%= form.label :input_name, "Ime", class:"form-label" %>
          <%= form.text_field :input_name, :required => true, :minlength => 2, class:"form-control", value:current_user.first_name + " " + current_user.last_name %>
        </div>

        <div class="mb-3">
          <%= form.label :input_email, "Email", class:"form-label" %>
          <%= form.email_field :input_email, :required => true, :minlength => 5, class:"form-control", value: current_user.email %>
        </div>

        <div class="mb-3">
          <%= form.label :input_card_num, "Broj kartice", class:"form-label" %>
          <%= form.text_field :input_card_num, :required => true, :minlength => 10, class:"form-control"%>
        </div>

        <%= form.submit "Kupi", class:"btn btn-dark", style:"background-color: #de3b09" %>
      <% end %>
    </div>
    <div class="col d-flex justify-content-center">
      <div class="card w-50" style="align:center">
        <h5 class="card-header">Karta</h5>
        <div class="card-body">
          <p class="card-text">Prijevoznik: <%= @transport.company.name %></p>
          <p class="card-text">Polazak: <%= @transport.departure.strftime("%d/%m/%Y %H:%M") %></p>
          <p class="card-text">Dolazak: <%= @transport.arrival.strftime("%d/%m/%Y %H:%M") %></p>
          <p class="card-text">Cijena: <%= @transport.price %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1>Dostupni prijevozi</h1>

<table class="table table-sm table-striped table-hover align-middle">
  <thead>
    <tr>
      <th>Prijevoznik</th>
      <th>Polazak</th>
      <th>Dolazak</th>
      <th>Preostalo karata</th>
      <th>Cijena</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @transports.sort %>
    <% @transports.each do |transport| %>
      <% available_tickets = transport.nTickets - transport.tickets.length %>
      <tr>
        <td><%= transport.company.name %></td>
        <td><%= transport.departure.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= transport.arrival.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= available_tickets %></td>
        <td><%= transport.price %></td>
        <% if available_tickets > 0 %>
          <td><%= link_to "Kupi", checkout_path(transport), class:"btn btn-dark", style:"background-color: #de3b09" %></td>
        <% else %>
          <td><a class="btn btn-dark disabled", style="background-color: #756d6d" aria-disabled="true"> Kupi </a></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/user_tickets.html.erb
<h1>Moje karte</h1>

<table class="table table-sm table-striped table-hover align-middle">
  <thead>
    <tr>
      <th>Prijevoznik</th>
      <th>Polazak</th>
      <th>Dolazak</th>
      <th>Cijena</th>
      <th>Ime</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% current_time = Time.new() %>
    <% @tickets.each do |ticket| %>
      <% transport = ticket.transport %>
      <tr>
        <td><%= transport.company.name %></td>
        <td><%= transport.departure.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= transport.arrival.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= transport.price %></td>
        <td><%= ticket.name %></td>
        <td><%= ticket.email %></td>
        <% if (transport.departure - current_time) < 3600 %>
          <td><a class="btn btn-dark disabled", style="background-color: #756d6d" aria-disabled="true"> Otkaži </a></td>
        <% else %>
          <td><%= link_to "Otkaži", cancel_ticket_path(ticket), method: :delete, data: { confirm: "Jeste li sigurni?" }, class:"btn btn-dark", style:"background-color: #de3b09"%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #de3b09">
  <div class="container-fluid">
    <%= link_to "SKK Karte", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if user_signed_in? %>

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Moj profil", edit_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Moje karte", user_tickets_path, class:"nav-link" %>
          </li>
        </ul>

        <span class="navbar-text pe-4"><%= current_user.first_name + ' ' + current_user.last_name %></span>
        
        <ul class="navbar-nav me-2 mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Odjava", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        </ul>   

      <% else %>

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Registracija", new_user_registration_path, class:"nav-link" %>
          </li>
        </ul>

        <ul class="navbar-nav me-2 mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Prijava", new_user_session_path, class:"nav-link" %>
          </li>
        </ul>

      <% end %>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SKKTickets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= render 'layouts/header' %>
    
    <br/>

    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>

    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>